export const AUTHENTICATION_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export const TASK_ACTIONS = {
  GET_TASKS: 'GET_TASKS',
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK'
};

export const USER_ACTIONS = {
  GET_USERS: 'GET_USERS'
};
